// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(GradiumDbContext))]
    [Migration("20250924124606_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Core.Models.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssessmentMaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssessmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("AssessmentWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssessmentId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Core.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassGrade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClassYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClassId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Core.Models.Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Core.Models.Marksheet", b =>
                {
                    b.Property<int>("MarksheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarksheetIssuedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MarksheetId");

                    b.HasIndex("ClassId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Marksheets");
                });

            modelBuilder.Entity("Core.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentCemisId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Core.Models.StudentMark", b =>
                {
                    b.Property<int>("MarksheetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssessmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentMarkId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StudentMarkScore")
                        .HasColumnType("REAL");

                    b.HasKey("MarksheetId", "StudentId", "AssessmentId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentMarks");
                });

            modelBuilder.Entity("Core.Models.Template", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemplateGrade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateSubject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("TemplateId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Core.Models.Assessment", b =>
                {
                    b.HasOne("Core.Models.Template", "Template")
                        .WithMany("Assessments")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Core.Models.Enrollment", b =>
                {
                    b.HasOne("Core.Models.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Core.Models.Marksheet", b =>
                {
                    b.HasOne("Core.Models.Class", "Class")
                        .WithMany("Marksheets")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Template", "Template")
                        .WithMany("Marksheets")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Core.Models.StudentMark", b =>
                {
                    b.HasOne("Core.Models.Assessment", "Assessment")
                        .WithMany("StudentMarks")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Marksheet", "Marksheet")
                        .WithMany("StudentMarks")
                        .HasForeignKey("MarksheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Student", "Student")
                        .WithMany("StudentMarks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Marksheet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Core.Models.Assessment", b =>
                {
                    b.Navigation("StudentMarks");
                });

            modelBuilder.Entity("Core.Models.Class", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Marksheets");
                });

            modelBuilder.Entity("Core.Models.Marksheet", b =>
                {
                    b.Navigation("StudentMarks");
                });

            modelBuilder.Entity("Core.Models.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("StudentMarks");
                });

            modelBuilder.Entity("Core.Models.Template", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Marksheets");
                });
#pragma warning restore 612, 618
        }
    }
}
